executable            = convert_ghep_gst.sh
arguments             = $(ProcId) sndlhc_+volAdvTarget_100_ADVSNDG18_02a_01_000.0.ghep.root
output                = logs/convert_ghep_gst.$(ClusterId).$(ProcId).out
error                 = logs/convert_ghep_gst.$(ClusterId).$(ProcId).err
log                   = logs/convert_ghep_gst.$(ClusterId).log
getenv = True
notification = Never
RequestCpus = 1
requirements = (OpSysAndVer =?= "AlmaLinux9")
+JobFlavour             ="longlunch"
queue 10
